---
title: '2019-04-10'
author: "林茂廷"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("stringr")
library(stringr)
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
```

```{r}
str_subset(course,"經濟學")
```

```{r}
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
str_sub(studentID , 5 ,6 )
str_sub(studentID , 2 , 4)
```

```{r}
month <- c("3" , "4" , "6")
day <- c("13" ,"14" ,"16")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
month
day
str_c(month,day, sep="-")
```

```{r}
dates <- c("3-11", "4-5",  "2-7")
str_split(dates,"-")
```

```{r}
dates
str_replace(dates,"-","月")
```

```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

```{r}
install.packages("readr")
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
str_c("http://github.com/",username,"/",reponame)
```

```{r}
install.packages("readr")
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
head(birthday)
year<-str_sub(birthday,1,4)
month<-str_sub(birthday,5,6)
day<-str_sub(birthday,7,8)
str_c("西元",year,"年",month,"月",day,"日")
```

```{r}
y<-str_sub(birthday,1,4)
m<-str_sub(birthday,5,6)
d<-str_sub(birthday,7,8)
bday<-str_c("西元",y,"年",m,"月",d,"日")
bday
mm<-str_replace(bday,"年0","年")
dd<-str_replace(mm,"月0","月")
dd


date<-c("099/01","099/02","099/03")
library(lubridate)
year<-str_sub(date,1,3)
year<-as.numeric(year)
ys<-years(year+1911)
ms<-str_sub(date,5,6)
dates<-str_c(str_sub(ys,1,4),m,sep="/")
dates
```

```{r}
a<-c(1:3)
typeof(a)
a
```

```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(a)
aWithNames
```

```{r}
b1<-list("a","b",c(1:10))
typeof(b1)
```

```{r}
b2<-list(
  第一個="a",
  第二個="b",
  第三個=c(1:10))
```

```{r}
b1
b2
```

