---
title: '2019-04-03'
author: "林茂廷"
date: "3/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```
```{r}
x3 == y3
x3 != y3
```
! negation
```{r}
x3 == y3
!(x3 == y3)
```
```{r}
install.packages("readr")
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
```{r}
head(currency) 
```
```{r}
class(currency)
```
```{r}
currency <- as.factor(currency)
class(currency)
```

```{r}
levels(currency)
```
```{r}
length(levels(currency))
```
```{r}
currency2 <- c("日圓","美國","日圓")
currency2
```

```{r}
sum(currency2 == "日圓")
```
```{r}
head(currency)
sum(currency == "日圓JPY/USD")
```
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```

```{r}
x5 %in% greatTaipei
y5 == "女"
(x5 %in% greatTaipei) & (y5=="女")
```

```{r}
which((x5 %in% greatTaipei) & (y5=="女"))
```

```{r}
x5
y5

(x5 %in% greatTaipei) | (y5=="女")
```

```{r}
which((x5 %in% greatTaipei) | (y5=="女"))
```
```{r}
xor(x5 %in% greatTaipei, y5=="女")
```

```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

```{r}
class(date)
```

```{r}
head(date)
```

```{r}
library(lubridate)
date <- ymd(date)
class(date)
```

```{r}
isAfter19800801 <-
  date >= ymd(  "1980-08-01")
isAfter19800801
```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```

```{r}
class(isAfter19800801)
sum(isAfter19800801)
```

```{r}
head(currency)

```

```{r}
head(currency == "歐元USD/EUR"

isEURO <- currency == "歐元USD/EUR"
```

```{r}
sum(isEURO)
```

```{r}
head(exchangeRate)
is.na(exchangeRate)
sum(is.na(exchangeRate))
```

```{r}
currency == "歐元USD/EUR" & ! is.na(exchangeRate)
sum(currency == "歐元USD/EUR" & ! is.na(exchangeRate))
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```

```{r}
sum(major == "經濟學系")
```

```{r}
sum(studentID == "5bdS6977b")
```

```{r}
sum(studentID == "5bdS6977b" & grade >=60 )
```

```{r}
sum(major == "經濟學系" & courseType == "選")
```

```{r}
sum(major == "經濟學系" & courseType == "必") ->mn
mn
```

```{r}
sum(major == "經濟學系" & courseType == "必"& grade < 60) -> sn
sn
```

```{r}
sn/mn
```








```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
typeof(studentMajors)
levels(studentMajors)
studentMajors
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```

```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
class(dtObject)
dtObject
```

semester100 <- schoolYear == 100
semester100