---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---

```{r}
Vec1 <- c(1:6)
Vec1
```

```{r}
Mat1 <- matrix(
  c(1:6) , 2,3
)
Mat1
class(Mat1)
typeof(Mat1)
Mat1[[2]]
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d") ,2 ,2
  
)
Mat2
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
class(StuDF$姓名)
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
StuDF[[2]][[3]]
```

```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
```

```{r}
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```

```{r}
StuDF4
```

```{r}
LETTERS
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
matObj1[[8]]

```

```{r}
matObj1
matObj1[3,2] 
matObj1[c(1,5),c(2,3)]
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
dim(classSurvey)
nrow(classSurvey)
ncol(classSurvey)
classSurvey[c(1:60),c(4,5)]
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
```

```{r}
colnames(StuDF2)[c(2,3)] <- c("姓名","成績")
colnames(StuDF2)
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]] <- FALSE
b[[5]] <- 7
b
```

```{r}
library(readr)
library(lubridate)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 >= ymd("1997-06-01") & exData3$期間 <= ymd("1998-12-01")
class(exData3$isAsiaCrisis)
```

```{r}
exData3[exData3$isAsiaCrisis ==T ,]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
names(transcriptDataFinal)
transcriptDataFinal[transcriptDataFinal$學號 == "92aS67fee",]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
class(utility_cobb_douglass)
```

```{r}
function1 <- function(x, .alpha){
  functionvalue <- x+.alpha
  return(functionvalue)
}

class(function1)
function1(2,4)
```

```{r}
supply_fun<- function(a,b,P){
  Qs<-a+b*P
  return(Qs) 
}
demand_fun<- function(c,d,P){
  Qd<-c-d*P
  return(Qd) 
}
demand_fun(5,1,1)
supply_fun(0,1,1)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun( "105S60ba1")
```
