---
title: "midterm correct"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate); library(stringr); library(dplyr); library(readr); library(purrr)
```


```{r}
randomGrades <- sample(40:80,15,replace = T)
randomCredits <- sample(0:3,15,replace=T)
data3 <- list(
  成績=randomGrades,
  學分數=randomCredits
)
```

```{r}
passLogic <- data3$成績>=60
map(data3,~.[passLogic]) -> passData
passData
```

```{r}
sample(99:103,15,replace = T)-> yy
sample(1:12,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
```

```{r}
twDates1 <- str_replace(twDates,"民國","")
twDates2 <-str_replace(twDates1,"月","")
twDates2
```

```{r}
str_split(twDates2,"年") -> dateList
map(dateList,~.[[1]]) -> yy
as.integer(yy)+1911 -> westYears

westYears
```

```{r}
load("invoiceList.Rda")
names(invoiceList) <-
  c('訂單時區','訂單時間(以訂單時區顯示)','UTC時間')
```

```{r}
names(invoiceList)[[2]] <- "訂單時區之下單時間"
invoiceList
```

```{r}
(invoiceList$訂單時區=="America/New_York") -> nyLogical
(invoiceList$訂單時區=="Asia/Taipei") -> tpLogical

invoiceList$UTC時間[nyLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[nyLogical],
          tz="America/New_York"),tzone="UTC")
invoiceList$UTC時間[tpLogical] <-
  with_tz(ymd_hms(invoiceList$`訂單時區之下單時間`[tpLogical],
          tz="Asia/Taipei"),tzone="UTC")

invoiceList 
```

```{r}
load("sampledTranscriptData.Rda")
names(sampledTranscriptData) <- 
  c('學號','學期成績','學分數','學年','學期','必選修類別（必／選／通）','系級','科目名稱','年級','學屆')
```

```{r}
(sampledTranscriptData$科目名稱 == "科目204") -> chosenSubjectLogi
sampledTranscriptData$學期成績[chosenSubjectLogi] -> chosenGrades
sum(chosenGrades<60)/length(chosenGrades) -> failRate

failRate
```

```{r}
sampledTranscriptData$學屆 <- 
  str_sub(sampledTranscriptData$學號,2,4)
sampledTranscriptData$系碼 <- 
  str_sub(sampledTranscriptData$學號,5,6)

sampledTranscriptData
```

```{r}
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$系級,"1","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"2","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"3","")
sampledTranscriptData$學系 <- str_replace(sampledTranscriptData$學系,"4","")

sampledTranscriptData$學系 
```

```{r}
(sampledTranscriptData$系碼!="73" & 
   sampledTranscriptData$學系=="經濟學系") -> logiCheck
sampledTranscriptData$學號[logiCheck] %>% unique() -> changeMajorStudent

changeMajorStudent
```

```{r}
(sampledTranscriptData$學號 == "410073409b" &
  sampledTranscriptData$學年==101 &
  sampledTranscriptData$學期==1) -> logiSelect
  
sum(sampledTranscriptData$學分數[logiSelect]*
  sampledTranscriptData$學期成績[logiSelect])/sum(sampledTranscriptData$學分數[logiSelect]) -> studentGPA

studentGPA
```
