---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
Vector1[["名稱4"]]
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)

colnames(StuDF2) <- c("col1","col2","col3")

colnames(StuDF2)[[2]] <- c("姓名")

colnames(StuDF2)[c(2,3)] <- c("name","grade")

StuDF2
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在

a[[3]] <- "FALSE"
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)

b$元素3 <- FALSE
b[[3]]
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
time3<- exData3$期間
time3<- ymd(time3)
time3-> exData3$期間

class(exData3$期間)
```

